### ISSUE TITLE
Unable to convert MySQL date/time value to System.DateTime

### ISSUE THREAD

**Issue by LuigiElleBalotta** [Arctium-Software/LappaORM#21]
Programs throw this exception when you have an object property DateTime and MySQL Column Date/Timestamp

**Comment by Fabi** [comment]
Fixed with allow zero datetime=true?

**Comment by LuigiElleBalotta** [comment]
yes

**Comment by LuigiElleBalotta** [comment]
well, you have to set another thing in that string also, but now I don't have to code
