### ISSUE TITLE
No objects are returned on simple Select commands

### ISSUE THREAD

**Issue by Fabi** [Arctium-Software/LappaORM#3]
Used ORM method: `Database.Single<Account>(a => a.Email == "test@test.com")`
Generated sample: `SELECT * FROM Accounts WHERE (Email = 'test@test.com')`
Table info: 1 row in Accounts table.
Connector: https://github.com/mysql-net/MySqlConnector

It should return 1 object in EntityBuilder.CreateEntities, but it always returns 0.

**Comment by LuigiElleBalotta** [comment]
Try to use Any or First, I already noticed this error long time ago, but there was a workaround..
